#
# This compose file is ment for developers only.
#

name: utm-builder-dev # Will be used for auto naming (network, volume names)
services:
  app:
    extends:
      file: compose.base.yaml
      service: app
    image: 192.168.84.20:8082/utm-builder:latest
    pull_policy: always # Compose always pulls the image from the registry.
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3131:3000 # These ports are in format <host-port>:<container-port>
  db:
    extends:
      file: compose.base.yaml
      service: db
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db #Volume mapping for persistency

volumes: # It will prepend the project name
  mongodb: