name: utm-builder # Will be used for network auto naming and image names
services:
  app:
    image: 192.168.84.16:8082/utm-builder-dev:latest
    container_name: utm-builder-dev
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3131:3000' # These ports are in format <host-port>:<container-port>
  db:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_USER}
      # MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASS}
      # MONGO_INITDB_DATABASE: utm-builder
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      start_period: 5s
#    ports:
#      - 27017:27017
    volumes:
      - mongodb:/data/db #Volume mapping for persistency

volumes:
  mongodb: # It will prepend the project name
#  nexus:



#      ME_CONFIG_BASICAUTH_USERNAME: basicusername
#      ME_CONFIG_BASICAUTH_PASSWORD: basicusernamepass

