apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngnix-test
  labels:
    app.kubernetes.io/name: ngnix-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ngnix-test
  template:
    metadata:
       labels:
        app.kubernetes.io/name: ngnix-test
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ngnix-test
spec:
  selector:
    app.kubernetes.io/name: ngnix-test
  type: LoadBalancer #this type makes the service external
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080