apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontendService.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.frontendService.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.frontendService.name }}
  template:
    metadata:
       labels:
        app.kubernetes.io/name: {{ .Values.frontendService.name }}
    spec:
      containers:
      - name: {{ .Values.frontendService.name }}
        image: {{ .Values.appImage }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.frontendService.containerPort }}
        env:
        {{- toYaml .Values.frontendService.env | nindent 8 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontendService.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.frontendService.name }}
  type: LoadBalancer #this type makes the service external
  ports:
    - protocol: TCP
      port: {{ .Values.frontendService.servicePort }}
      targetPort: {{ .Values.frontendService.containerPort }}